### ISSUE TITLE
Missing trap?

### ISSUE THREAD

**Issue by AndrewFarley** [Chia-Network/chia-docker#147]
The docker-entrypoint.sh is missing a "trap" to capture signals to cascade them down into docker-start, which would then cleanly shut down the node.  As it stands right now, signals are not being captured and the node is not cleanly shutting down.  Unless I'm mistaken and there's something somewhere I'm unaware of.

**Comment by cmmarslender** [comment]
Trap is in the docker-start file, which is called as the cmd by default https://github.com/Chia-Network/chia-docker/blob/main/docker-start.sh#L6

**Comment by AndrewFarley** [comment]
@cmmarslender  "entrypoint" is the command that is executed first, which then calls docker-start as a sub-process.  However, the parent process is the one that receives the signals from Docker/Kubernetes, not all child processes retroactively.  I'm fairly certain without a trap in the entrypoint, no trap will ever be sent and thus chia will not be shut down cleanly.

**Comment by cmmarslender** [comment]
Testing this locally with docker, it works both running in the foreground (and quitting with ctrl + c) as well as running in the background with -d and running `docker stop <container_id>`. Either results in `Shutting down ...` and eventually `daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '3122113dc0689c7aa9d97cb25500b395660840facbb4897a77555bb5cebde73a'}`

Its definitely possibly something different is going on when running in kubernetes though, I'll take a look at that. 

The reason we put this in the start vs entrypoint was in the case where someone might be running this container as a plotter or something where chia isn't really running in the background (overriding the default command with a different command). In that case, the trap that runs `chia stop -d all` doesn't really make sense, since chia may not be running to begin with. 

I'll post back results here after I test in k8s as well.

**Comment by cmmarslender** [comment]
Ok - just tested kubernetes. Just did a basic `kubectl run chia --image chianetwork/chia-docker:latest` and let the container come up, then `kubectl delete pod chia`, and saw the output of the trap there as well: `Shutting down ...` and eventually the message from the daemon.

Any chance you're overriding the `args` in your kubernetes manifest or changing the way this container starts?

**Comment by AndrewFarley** [comment]
@cmmarslender Ah apologies, closing as an non-issue.  I was doing something custom over here, with the regular container I'm seeing trapped signals now.  Thanks
