### ISSUE TITLE
Refine GitHub package  build logic to not spam new tags every hour

### ISSUE THREAD

**Issue by Artanicus** [Chia-Network/chia-docker#155]
Currently there are 1.3k+ tags on the `chia-network/chia` image. (https://github.com/Chia-Network/chia-docker/pkgs/container/chia/versions) Not only does it make very hard to find the right tag by hand, it also seems the registry API is starting to work a bit wonky with this many tags. For example, while the `1.3.1` tag does exist and can be pulled, the API call for listing tags no longer returns it:
```
%> curl -sH "Authorization: Bearer NOOP" https://ghcr.io/v2/Chia-Network/chia/tags/list | tr , \\n | egrep '"[0-9.]+"'

"1.0.0"
"1.0.1"
"1.0.2"
"1.0.3"
"1.0.4"
"1.0.5"
"1.1.0"
"1.1.1"
"1.1.2"
"1.1.3"
"1.1.4"
"1.1.6"
"1.1.7"
"1.2.6"
"1.2.7"
"1.2.8"
"1.2.9"
"1.2.10"
```

Could the image workflow be adjusted to not tag quite as many automated images? Untagged images are still also available with their commit hash, for example `[sha256:6a0ab9f17bb954ae7698fefeaa7f4e9e42bdcac73699d41705fd2d9a4aaef952](https://github.com/orgs/Chia-Network/packages/container/chia/19182316)

**Comment by Starttoaster** [comment]
Hi @Artanicus, the way the registry API is supposed to work is through paginated requests. By design, GitHub (actually Docker, but GitHub followed Docker's standard) only returns a subset of tags from that API endpoint. You're supposed to iterate through in a loop to determine an actual all encompassing list of image tags. See: https://docs.docker.com/registry/spec/api/#listing-image-tags

If GitHub is not handling pagination correctly on that endpoint, that's something they should fix :)

> Not only does it make very hard to find the right tag by hand

The documentation within the readme of this repo suggest using `:latest` as the desired tag. This is because `:latest` here should match the `latest` ref on the Chia-Blockchain repository. Granted you also have the option of tagging to a specific semver (eg. `1.3.3`)

> Untagged images are still also available with their commit hash

Those commit hash tagged images are created when somebody opens a pull request on the main `chia-blockchain` repo in this workflow https://github.com/Chia-Network/chia-blockchain/blob/main/.github/workflows/trigger-docker-dev.yml

The reason those image tags exist would be to verify that whatever change you've made could be built over here. And if you would like to manually verify anything from the chia-docker image, you can pull the resulting image down and test it locally.

**Comment by Artanicus** [comment]
Gotcha. It still however makes the GitHub packages UI almost useless. I only went to the API to figure out what numbered tags exist since it was impossible to actually see it from the tag list. I'm not convinced the PR builds need to be tagged since they can be referred to by hash.

**Comment by Starttoaster** [comment]
> It still however makes the GitHub packages UI almost useless.

I agree with this. It's unfortunate that many aspects of GitHub's UI is not very friendly to users, especially when the UI starts getting populated with data. I was talking to a peer about this Issue and we all agree the experience around viewing tags could be improved. I created https://github.com/Chia-Network/chia-docker/pull/157 to pollute the image registry for the `chia` image less. After some time passes and the old commit SHA images start to become stale I'd suggest we also clean those up a little to make searching for image tags easier.

**Comment by Artanicus** [comment]
Looking at the package page now I believe the issue has been resolved and the recent published images are well visible on the first page of results both in the preview and full version list. Will leave open in case you want to use this to track the history purge.
