### ISSUE TITLE
`~/.chia_keys` is Undocumented

### ISSUE THREAD

**Issue by optix2000** [Chia-Network/chia-docker#167]
The Readme only talks about mounting `~/.chia/` or `~/.chia/mainnet/` when keeping a persistent config.

However, the keys from `chia keys generate` are actually stored in `~/.chia_keys/` not ~/.chia/`. This means that restarting the container will lose your keys.

**Comment by Starttoaster** [comment]
I think it's likely that this is not documented because there are other methods available to persist your keys. For example, you can specify the `keys` environment variable as a path to a file containing your mnemonic, which will initiate the `chia keys add` command any time your container is restarted (see: https://github.com/Chia-Network/chia-docker/blob/main/docker-entrypoint.sh#L34)

I'm possibly open to this being documented too, though. I asked a bit internally to gather more opinions about this.

**Comment by Starttoaster** [comment]
Asked around, it seems like this wasn't documented before because `~/.chia_keys` wasn't always a directory that was created. It seems appropriate to document it, despite there being other options to persist your keys. I raised a PR to do so.
