### ISSUE TITLE
Error in log after upgrading to 1.7.0

### ISSUE THREAD

**Issue by santivu** [Chia-Network/chia-docker#194]
Hi,

I was alwais using without any issut the docker as harvester, using the recoomended settings, specially for ca and keys variables.
Now I see this server.py error every time I restart the docker and seems to be related with the value "copy" inside keys.
Still the harvester seems to work fine.
Thanks!

![error](https://user-images.githubusercontent.com/88079415/224685857-b94d1483-dee3-43a5-83f3-4714f258d3be.jpg)

**Comment by Starttoaster** [comment]
Hey there! Thanks for reporting this. There were some changes to the startup script recently that removed the need for setting the variable `keys` to `copy`. If you just remove the `keys` variable from your  configuration it will continue to work. Sorry for the confusion there, it wasn't actually intended for that error message to begin showing up :)

In the meantime, we added a conditional that looks for a `keys=copy` environment variable and it just returns a short deprecation message instead of the error. If you pull a new version of the image, it should be updated.

To be clear, the functionality of running a harvester-only container is _not_ being deprecated. Just that environment variable with the value "copy"

**Comment by santivu** [comment]
Super! Many thanks for your response.
I updated the docker image, keeping the keys=copy and as you said, now there is a new deprecated message, that is fine.
I tried also to remove the variable, but then the warnings about private keys appeared. I know there are normal and in fact good an dmore secure for farming, but you know. Always prefering a clean log.



![1](https://user-images.githubusercontent.com/88079415/224815201-711e0cba-5b3f-418e-bb20-85116a52f8f7.jpg)
![2](https://user-images.githubusercontent.com/88079415/224815214-a78c2f4b-9481-400b-869b-310a6285a526.jpg)

**Comment by Starttoaster** [comment]
Really good call out again! Thanks for being patient with me (it is a Monday, after all :) )

For a harvester-only setup `keys=none` would actually be the preferred setup. I rescind the `remove the keys variable` portion of my previous advice :smile:

**Comment by santivu** [comment]
HAHAHAHA, that's fine ;-)
Now it's perfect.
I really appreciate this fast suport.
Warm regards,


![imagen](https://user-images.githubusercontent.com/88079415/224823548-a5b63800-b1aa-48fe-9624-8c237ed86d4a.png)

**Comment by Starttoaster** [comment]
You're welcome and thanks for the good reports. Have a nice week :)
