### ISSUE TITLE
Possible issue with port forwarding and wallet sync on latest image.

### ISSUE THREAD

**Issue by BiskaWolf** [Chia-Network/chia-docker#203]
Hi all, 

I've just done a fresh install of TrueNAS Scale, and deployed/install the latest Official Chia pod/container onto the system (version 1.8.1, 1.0.10).

The Full Node is syncing fine, however the Wallet does not appear to be syncing at all. Also, it looks like the Port Forwarding on the container isn't working. I've correctly got ports 8444 and 8447 forwarded to 38444 and 38447, but they don't appear as being opened. I've tested with other application ports, and port forwarding on the host is working correctly for those other apps. 

![Chia Pod Logs](https://github.com/Chia-Network/chia-docker/assets/1871742/de8db1b8-d912-47f5-8a76-0243867d3f80)

**Comment by cmmarslender** [comment]
Hello,

You shouldn't need ports forwarded to the wallet in order for it to sync, so I'm not sure that is the issue here. The logs are indicating that every peer the wallet is trying to connect with is not synced, which seems like a different problem (admittedly weird and unexpected that you would hit that many un-synced peers in a row).

I tested the 1.8.1 chia-docker container outside of the truenas context and was able to get the wallet synced without any issues
`docker run --rm -it -e service=wallet -e log_level="INFO" chianetwork/chia-docker:1.8.1`

It seems like this may be an issue specific to running this on TrueNAS, but you could possibly try removing the wallet_peers.dat file (in `~/.chia/mainnet/wallet/db` or whatever your equivalent path would be) and then restarting the container to see if maybe you just have a bunch of bad peers in your peer list
