### ISSUE TITLE
Remote GUI no longer works

### ISSUE THREAD

**Issue by shiftybee** [Chia-Network/chia-docker#210]
Every time the container is composed, the config.yaml is re-written, and "self_hostname: 127.0.0.1" is reset.   

My current workaround which works until the container is re-created:

Start the container
enter the container via "docker exec -it containername /bin/bash"
run "chia stop farmer -d"
modify the file to "self_hostname: 0.0.0.0"
run "chia start farmer -r"

Top modify the file you'll either need to install an editor in the container, or edit it in another window on the host machine.

**Comment by Starttoaster** [comment]
The `self_hostname` value in the config is getting set to 127.0.0.1 as that's the default value for the container. You can set the `self_hostname` environment variable to `0.0.0.0` rather than edit the config each time you restart the container, and the entrypoint script will set that value in the config without a text editor.

**Comment by Starttoaster** [comment]
:smile: I was actually under the assumption that it was documented already, I just made a PR to add that in, good suggestion, thanks.
