### ISSUE TITLE
Docs update for boolean env vars with docker compose

### ISSUE THREAD

**Issue by rocketeerbkw** [Chia-Network/chia-docker#220]
The true/false environment variables used in the [example section for docker-compose](https://github.com/Chia-Network/chia-docker/blob/main/readme.md?plain=1#L186) must be quoted to prevent them from being interpolated as booleans. From the [compose spec](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#environment):

> Any boolean values; true, false, yes, no, should be enclosed in quotes to ensure they are not converted to True or False by the YAML parser.

If you were to copy the example and uncomment the `upnp` environment variable, docker-compose will fail:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.chia.environment.upnp contains true, which is an invalid type, it should be a string, number, or a null

This was introduced in #154 where the previous environment variable syntax using arrays already treats the entire value as a string, but the new syntax using maps doesn't.

Previous valid array syntax:
```
environment:
  - upnp=true
```
Current invalid map syntax:
```
environment:
  upnp: true
```
Suggested valid map syntax:
```
environment:
  upnp: "true"
```

**Comment by Starttoaster** [comment]
Thanks for fixing this! I'm sure many people in the future would thank you :)

**Comment by Starttoaster** [comment]
Apparently I had reached a point last night where I was tired enough to not realize that the auto-merge didn't go through last night after I approved your PR 😄  @rocketeerbkw if you don't mind would you sign your commit? It's a requirement for contributions to chia-network repositories, so I unfortunately am unable to merge it until then. Alternatively, I could open a PR with your documentation change myself but I prefer not doing that because it doesn't show up as a contribution on your behalf and I'd like you to receive your credit where it's due :)

**Comment by Starttoaster** [comment]
Thank you for the report! Since we didn't get a response back from you, I just went ahead and did the documentation fix so other users don't get confused by this in the future.
