### ISSUE TITLE
Wrong time zone/time?

### ISSUE THREAD

**Issue by adammcgee** [Chia-Network/chia-docker#28]
This whole thing is new to me, but my time seems to be wrong. Not sure if this has any affect on the node but it seems to think my time zone in UTC. Any way to correct this?

**Comment by o6uoq** [comment]
UTC is standard time zone to be set for an operating / system image.

Chia uses a base image of **Ubuntu 20.04.2 LTS**. Example:

```
$ docker run --rm -it ubuntu /bin/bash
root@e19ef059baaf:/# date
Tue May  4 16:43:52 UTC 2021
```

Unless you think this is impacting your farm/harvest, I wouldn't worry about it.

**Comment by horego** [comment]
@adammcgee i forked the chia-docker repo and fixed the time(zone) problem. Feel free to give it a try. On my system everything is now workling like a charm. Docker image is build through github workflow. In the past i had problems due to wrong time(zone). You can pull it from packages or build it on your own.

They should add 
`RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
`
to dockerfile.

Repo: https://github.com/horego/chia-docker
