### ISSUE TITLE
Please don't use environment variables for secrets like this

### ISSUE THREAD

**Issue by snikch** [Chia-Network/chia-docker#5]
Hi there, I'd suggest another method for providing the mnemonic words. Having them in the environment like this will add them to people's log and bash history etc. which is a significant concern. It can also expose them through careless use of commands like `env` in the container.

I'd suggest reading from a mounted file, which can be defined via an env var, e.g.

```
docker exec  ... -e MNEMONIC_FILE=/var/secrets/mnemonic.txt …
```

Note, this would also be compatible with Docker Swarm and Docker Compose's native secrets handling.

**Comment by justinengland** [comment]
Hey! So this is a flaw in the chia keys add command its self. Ingesting from a text file is on the list. but for now my understanding is the keys must be added. I can make a change here to allow ingest from a file but this will be catting that file internally on the container. if you run 

docker exec -it chia venv/bin/chia keys add

this will run the command as it functions now via nix cli but inside the container, and you can paste your 24 words there and keep them out of your history. 

It is my assumption that in this case, if someone has access to your system to read your bash history, they have the keys to everything else as well, and can run "chia keys show" to get these keys that way as well. 

I think your point about other orchestration patterns is a fair one. I welcome a pr that solves that issue. Docker swarm and other patterns are not currently supported workflows. but as this is a beta, I would love to add them so that the community can run this container as they see fit.

**Comment by snikch** [comment]
Interestingly with my docker setup, I actually just mount in the parent keyring and config dir which means I have no need to pass this info into the container via either means.

```
docker run --rm -it  -v ~/.chia:/root/.chia -v ~/.local/share/python_keyring/:/root/.local/share/python_keyring/ my_chia_image chia keys show
```

**Comment by justinengland** [comment]
this issue is resolved with the latest commits. Chia keys add now accepts flat text files. Closing issue. readme and docker image updated to run 1.0.2
