### ISSUE TITLE
Stable release instead of dev in "latest" tag.

### ISSUE THREAD

**Issue by GAS85** [Chia-Network/chia-docker#86]
Hello dear community,

currently we have tag `latest` that being used for latest **dev** releases, so version, e.g. `1.1.7` is not equal to `1.1.7.dev` and if I have a look on https://github.com/Chia-Network/chia-blockchain then latest version is `1.1.7`:

![grafik](https://user-images.githubusercontent.com/6813635/120989499-e879c300-c77f-11eb-8430-5edb475234f5.png)

But with docker tag `latest` I will receive `1.1.8.dev` already.

There is no tag to have latest stable version, besides to update it manually, e.g. `:1.1.7` and then `:1.1.8`...

My suggestion is to **not** use tag `latest` for dev software, but for actual stable version of software in sync with main channel https://github.com/Chia-Network/chia-blockchain e.g. `1.1.7`, not `1.1.8.dev`.

You can introduce tag `preview`, `dev` or `unstable` to use for `x.x.x.dev` releases.

Cheers!

**Comment by clreinki** [comment]
I 100% agree - dev versions should be on a different branch or at the very least not be under the "latest" tag

**Comment by Luiso0o** [comment]
I'm 100% agree!!

**Comment by lesinigo** [comment]
Also please try to stick to [SemVer](https://semver.org) if possible, for example by using tags like `1.2.4-dev.0` instead of `1.2.4.dev0`. The same would be cool with `chia` itself but at least starting with the docker images couldn't hurt.

**Comment by sfmike99** [comment]
Agree. Is there a way to pull the latest stable version (e.g. 1.1.7 instead of 1.1.8)?

**Comment by zcalusic** [comment]
Since this issue doesn't seem to move anywhere, now being 2 months without any progress, I decided to bite the bullet and prepare an unofficial image which fixes this and several other issues I stumbled upon. If you feel like an adventurous type, be my guest and test it: https://github.com/zcalusic/dockerfiles/tree/master/chia It's much simpler, with almost 3 times smaller image, yet does so much more, at least for me. YMMV.

One more interesting thing, which I haven't even documented on the page above, 'cause it's rather spooky. While I was running the official image, I had NO incoming connection. Even after several days of interrupted run, 8 outgoing connection and none incoming. Of course, I checked that port 8444 is exposed. As soon as I switched to proper released version (as seen by chia version), now suddenly I have plenty incoming connections. I really can't tell is this because other nodes avoid nodes running development version, or something else. I really don't know... or care anymore. I feel very well connected, atm. :smiley:

**Comment by Luiso0o** [comment]
Agree. Is there a way to pull the latest stable version (e.g. 1.1.7 instead of 1.1.8)?

**Comment by GAS85** [comment]
Ping

**Comment by GAS85** [comment]
🧙 wrums - keep it open!

**Comment by cmmarslender** [comment]
`latest` tag corresponds to the `latest` branch in chia-blockchain repo, which is the most recently released version of chia. If the version is showing (version+1).dev0 its usually just because of a submodule issue - I'll see if I can get that resolved
