### ISSUE TITLE
docker container fails to start - connection error

### ISSUE THREAD

**Issue by gforceV** [Chia-Network/chia-docker#9]
After attempting to start the docker container Connection error.  docker exec -it chia venv/bin/chia show -s -c says "Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up"

The container logs show
" File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0,
Daemon not started yet
Starting daemon
Daemon not started yet
Failed to create the chia daemon"

There is nothing running on the docker host using port 8555.

**Comment by iwwwwwwi** [comment]
Seems simmilar to https://github.com/Chia-Network/chia-blockchain/issues/1535. It appears to be fixed in the latest version of docker image: https://github.com/Chia-Network/chia-docker/commit/9a3f5130196adf6a6908ef74c7073d173e79b374

have you tried to docker pull the latest image and only then start the container?

**Comment by justinengland** [comment]
this does appear to be fixed in the latest version of the container. Closing issue. please re open if this issue persists!
